ERP_Mensajeria/Controllers/RecepcionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ERP_Mensajeria.Models;

namespace ERP_Mensajeria.Controllers
{
    public class RecepcionesController : Controller
    {
        private ERPMensajeriaEntities db = new ERPMensajeriaEntities();

        // GET: Recepciones
        public ActionResult Index()
        {
            var recepcion = db.Recepcion.Include(r => r.Contacto).Include(r => r.Proveedor);
            return View(recepcion.ToList());
        }

        // GET: Recepciones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recepcion recepcion = db.Recepcion.Find(id);
            if (recepcion == null)
            {
                return HttpNotFound();
            }
            return View(recepcion);
        }

        // GET: Recepciones/Create
        public ActionResult Create()
        {
            ViewBag.ID_Contacto = new SelectList(db.Contacto, "ID_Contacto", "Nombre");
            ViewBag.ID_Proveedor = new SelectList(db.Proveedor, "ID_Proveedor", "Nombre");
            return View();
        }

        // POST: Recepciones/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Recepcion,ID_Contacto,ID_Proveedor,Tipo")] Recepcion recepcion)
        {
            if (ModelState.IsValid)
            {
                db.Recepcion.Add(recepcion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_Contacto = new SelectList(db.Contacto, "ID_Contacto", "Nombre", recepcion.ID_Contacto);
            ViewBag.ID_Proveedor = new SelectList(db.Proveedor, "ID_Proveedor", "Nombre", recepcion.ID_Proveedor);
            return View(recepcion);
        }

        // GET: Recepciones/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recepcion recepcion = db.Recepcion.Find(id);
            if (recepcion == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Contacto = new SelectList(db.Contacto, "ID_Contacto", "Nombre", recepcion.ID_Contacto);
            ViewBag.ID_Proveedor = new SelectList(db.Proveedor, "ID_Proveedor", "Nombre", recepcion.ID_Proveedor);
            return View(recepcion);
        }

        // POST: Recepciones/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Recepcion,ID_Contacto,ID_Proveedor,Tipo")] Recepcion recepcion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(recepcion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Contacto = new SelectList(db.Contacto, "ID_Contacto", "Nombre", recepcion.ID_Contacto);
            ViewBag.ID_Proveedor = new SelectList(db.Proveedor, "ID_Proveedor", "Nombre", recepcion.ID_Proveedor);
            return View(recepcion);
        }

        // GET: Recepciones/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Recepcion recepcion = db.Recepcion.Find(id);
            if (recepcion == null)
            {
                return HttpNotFound();
            }
            return View(recepcion);
        }

        // POST: Recepciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Recepcion recepcion = db.Recepcion.Find(id);
            db.Recepcion.Remove(recepcion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ERP_Mensajeria/Views/Recepciones/Create.cshtml
@model ERP_Mensajeria.Models.Recepcion

@{
    ViewBag.Title = "Crear recepción";
}
@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span><a href="@Url.Action("Index", "Recepciones")">Recepciones</a></span>
                    <span>/</span>
                    <span>Agregar recepción</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Recepcion nueva</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.ID_Contacto, "Contacto", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("ID_Contacto", null, htmlAttributes: new { @class = "md-form mdb-select" })
                                @Html.ValidationMessageFor(model => model.ID_Contacto, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ID_Proveedor, "Proveedor", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("ID_Proveedor", null, htmlAttributes: new { @class = "md-form mdb-select" })
                                @Html.ValidationMessageFor(model => model.ID_Proveedor, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Tipo, new SelectList(new List<Object>{
                                    new { value = "Entrada" , text = "Entrada"  },
                                    new { value = "Salida" , text = "Salida" }},
                                    "value", "text", 2), new { @class = "mdb-select md-form" })
                                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group text-right">
                            <div class="col-md-offset-2 col-md-10">
                                <a class="btn btn-primary" href="@Url.Action("Index", "Recepciones")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                                |
                                <button type="submit" class="btn btn-default"><i class="fas fa-magic ml-1"></i> Crear </button>
                            </div>
                        </div>
                    </div>
                }

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }
            </div>
        </div>
    </div>
}

ERP_Mensajeria/Views/Recepciones/Delete.cshtml
@model ERP_Mensajeria.Models.Recepcion

@{
    ViewBag.Title = "Eliminar recepción";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span><a href="@Url.Action("Index", "Recepciones")">Recepciones</a></span>
                    <span>/</span>
                    <span>Eliminar recepción</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                <div>
                    <h4>Recepción existente</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Tipo)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Tipo)
                        </dd>

                        <dt>
                            Contacto
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Contacto.Nombre)
                        </dd>

                        <dt>
                            Proveedor
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Proveedor.Nombre)
                        </dd>

                    </dl>

                    <hr />
                    <div class="text-center">
                        <h3>¿Desea eliminar ésta recepción?</h3>
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <a class="btn btn-primary" href="@Url.Action("Index", "Recepciones")">
                                    <i class="fa fa-arrow-left mr-1"></i> Regresar
                                </a>
                                |
                                <button type="submit" class="btn btn-danger">
                                    <i class="fa fa-times mr-1"></i>
                                    Eliminar
                                </button>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}

ERP_Mensajeria/Views/Recepciones/Details.cshtml
@model ERP_Mensajeria.Models.Recepcion

@{
    ViewBag.Title = "Detalles de la recepción";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span><a href="@Url.Action("Index", "Recepciones")">Recepciones</a></span>
                    <span>/</span>
                    <span>Detalles de la recepción</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                <div>
                    <h4>Recepción existente</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Tipo)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Tipo)
                        </dd>

                        <dt>
                            Contacto
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Contacto.Nombre)
                        </dd>

                        <dt>
                            Proveedor
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Proveedor.Nombre)
                        </dd>

                    </dl>
                </div>
                <br />
                <div class="form-group text-right">
                    <div class="col-md-offset-2 col-md-10">
                        <a class="btn btn-primary" href="@Url.Action("Index", "Recepciones")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                        |
                        <a href="@Url.Action("Edit", "Recepciones", new { id = Model.ID_Recepcion})" class="btn btn-default"><i class="fa fa-edit ml-1"></i> Editar </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

ERP_Mensajeria/Views/Recepciones/Edit.cshtml
@model ERP_Mensajeria.Models.Recepcion

@{
    ViewBag.Title = "Editar recepción";
}
@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span><a href="@Url.Action("Index", "Recepciones")">Recepciones</a></span>
                    <span>/</span>
                    <span>Editar recepción</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Recepcion existente</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.ID_Recepcion)

                        <div class="form-group">
                            @Html.LabelFor(model => model.ID_Contacto, "Contacto", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("ID_Contacto", null, htmlAttributes: new { @class = "md-form mdb-select" })
                                @Html.ValidationMessageFor(model => model.ID_Contacto, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ID_Proveedor, "Proveedor", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("ID_Proveedor", null, htmlAttributes: new { @class = "md-form mdb-select" })
                                @Html.ValidationMessageFor(model => model.ID_Proveedor, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Tipo, new SelectList(new List<Object>{
                                    new { value = "Entrada" , text = "Entrada"  },
                                    new { value = "Salida" , text = "Salida" }},
                                    "value", "text", 2), new { @class = "mdb-select md-form" })
                                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group text-right">
                            <div class="col-md-offset-2 col-md-10">
                                <a class="btn btn-primary" href="@Url.Action("Index", "Recepciones")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                                |
                                <button type="submit" class="btn btn-default"><i class="fa fa-save ml-1"></i> Guardar </button>
                            </div>
                        </div>
                    </div>
                }

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }
            </div>
        </div>
    </div>
}

ERP_Mensajeria/Views/Recepciones/Index.cshtml
@model IEnumerable<ERP_Mensajeria.Models.Recepcion>

@{
    ViewBag.Title = "Inicio";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span>Recepciones</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">

                <div class="row">
                    <div class="col-md-10">
                        <h2>Listado de recepciones</h2>
                    </div>
                    <div class="col-md-2">
                        <a class="btn btn-default btn-rounded" href="@Url.Action("Create", "Recepciones")">
                            <i class="fa fa-plus"></i> Crear
                        </a>
                    </div>
                </div>
                <br />
                <div class="table-responsive ">
                    <table class="table table-hover ">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Tipo)
                            </th>
                            <th>
                                Contacto
                            </th>
                            <th>
                                Proveedor
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Tipo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Contacto.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Proveedor.Nombre)
                                </td>
                                <td>
                                    <a class="btn btn-sm green" href="@Url.Action("Edit", "Recepciones", new { id = item.ID_Recepcion })">
                                        <i class="fa fa-edit"></i> Editar
                                    </a>
                                    <a class="btn btn-sm blue" href="@Url.Action("Details", "Recepciones", new { id = item.ID_Recepcion })">
                                        <i class="fa fa-eye"></i> Detalle
                                    </a>
                                    <a class="btn btn-sm red" href="@Url.Action("Delete", "Recepciones", new { id = item.ID_Recepcion })">
                                        <i class="fa fa-trash"></i> Eliminar
                                    </a>
                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
}