ERP_Mensajeria/Controllers/SolicitudProveedoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ERP_Mensajeria.Models;

namespace ERP_Mensajeria.Controllers
{
    public class SolicitudProveedoresController : Controller
    {
        private ERPMensajeriaEntities db = new ERPMensajeriaEntities();

        // GET: SolicitudProveedores
        public ActionResult Index()
        {
            var solicitudProveedor = db.SolicitudProveedor.Include(s => s.Proveedor);
            return View(solicitudProveedor.ToList());
        }

        // GET: SolicitudProveedores/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SolicitudProveedor solicitudProveedor = db.SolicitudProveedor.Find(id);
            if (solicitudProveedor == null)
            {
                return HttpNotFound();
            }
            return View(solicitudProveedor);
        }

        // GET: SolicitudProveedores/Create
        public ActionResult Create()
        {
            ViewBag.ID_Proveedor = new SelectList(db.Proveedor, "ID_Proveedor", "Nombre");
            return View();
        }

        // POST: SolicitudProveedores/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_SolicitudProveedor,ID_Proveedor,Fecha_Ingreso,Hora_Ingreso,Fecha_Creacion,Descripcion_Corta,Elevador,Estado_Entrega,Entregado,Aprobado,Tipo")] SolicitudProveedor solicitudProveedor)
        {
            if (ModelState.IsValid)
            {
                db.SolicitudProveedor.Add(solicitudProveedor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_Proveedor = new SelectList(db.Proveedor, "ID_Proveedor", "Nombre", solicitudProveedor.ID_Proveedor);
            return View(solicitudProveedor);
        }

        // GET: SolicitudProveedores/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SolicitudProveedor solicitudProveedor = db.SolicitudProveedor.Find(id);
            if (solicitudProveedor == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Proveedor = new SelectList(db.Proveedor, "ID_Proveedor", "Nombre", solicitudProveedor.ID_Proveedor);
            return View(solicitudProveedor);
        }

        // POST: SolicitudProveedores/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_SolicitudProveedor,ID_Proveedor,Fecha_Ingreso,Hora_Ingreso,Fecha_Creacion,Descripcion_Corta,Elevador,Estado_Entrega,Entregado,Aprobado,Tipo")] SolicitudProveedor solicitudProveedor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(solicitudProveedor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Proveedor = new SelectList(db.Proveedor, "ID_Proveedor", "Nombre", solicitudProveedor.ID_Proveedor);
            return View(solicitudProveedor);
        }

        // GET: SolicitudProveedores/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SolicitudProveedor solicitudProveedor = db.SolicitudProveedor.Find(id);
            if (solicitudProveedor == null)
            {
                return HttpNotFound();
            }
            return View(solicitudProveedor);
        }

        // POST: SolicitudProveedores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SolicitudProveedor solicitudProveedor = db.SolicitudProveedor.Find(id);
            db.SolicitudProveedor.Remove(solicitudProveedor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ERP_Mensajeria/Views/SolicitudProveedores/Create.cshtml
@model ERP_Mensajeria.Models.SolicitudProveedor

@{
    ViewBag.Title = "Crear solicitud de proveedor";
}
@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span><a href="@Url.Action("Index", "SolicitudProveedores")">Solicitudes de proveedor</a></span>
                    <span>/</span>
                    <span>Agregar solicitud de proveedor</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Solicitud de proveedor nueva</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.ID_Proveedor, "Proveedor", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.DropDownList("ID_Proveedor", null, htmlAttributes: new { @class = "md-form mdb-select" })
                                @Html.ValidationMessageFor(model => model.ID_Proveedor, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Fecha_Ingreso, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Fecha_Ingreso, new { htmlAttributes = new { @class = "form-control datepicker" } })
                                @Html.ValidationMessageFor(model => model.Fecha_Ingreso, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Hora_Ingreso, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Hora_Ingreso, new { htmlAttributes = new { @class = "form-control timepicker" } })
                                @Html.ValidationMessageFor(model => model.Hora_Ingreso, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Fecha_Creacion, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Fecha_Creacion, new { htmlAttributes = new { @class = "form-control datepicker" } })
                                @Html.ValidationMessageFor(model => model.Fecha_Creacion, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Descripcion_Corta, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Descripcion_Corta, new { htmlAttributes = new { @class = "md-form md-textarea" } })
                                @Html.ValidationMessageFor(model => model.Descripcion_Corta, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Elevador, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Elevador, new SelectList(new List<Object>{
                                    new { value = "Si" , text = "Si"  },
                                    new { value = "No" , text = "No" }},
                                    "value", "text", 2), new { @class = "mdb-select md-form" })
                                @Html.ValidationMessageFor(model => model.Elevador, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Estado_Entrega, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Estado_Entrega, new SelectList(new List<Object>{
                                    new { value = "En espera" , text = "En espera"  },
                                    new { value = "Aprobado" , text = "Aprobado"  },
                                    new { value = "Accesando" , text = "Accesando"  },
                                    new { value = "Saliendo" , text = "Saliendo" }},
                                    "value", "text", 2), new { @class = "mdb-select md-form" })
                                @Html.ValidationMessageFor(model => model.Estado_Entrega, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Entregado, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Entregado, new SelectList(new List<Object>{
                                    new { value = "Si" , text = "Si"  },
                                    new { value = "No" , text = "No" }},
                                    "value", "text", 2), new { @class = "mdb-select md-form" })
                                @Html.ValidationMessageFor(model => model.Entregado, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Aprobado, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Aprobado, new SelectList(new List<Object>{
                                    new { value = "Si" , text = "Si"  },
                                    new { value = "No" , text = "No" }},
                                    "value", "text", 2), new { @class = "mdb-select md-form" })
                                @Html.ValidationMessageFor(model => model.Aprobado, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Tipo, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Tipo, new SelectList(new List<Object>{
                                    new { value = "Entrada" , text = "Entrada"  },
                                    new { value = "Salida" , text = "Salida" }},
                                    "value", "text", 2), new { @class = "mdb-select md-form" })
                                @Html.ValidationMessageFor(model => model.Tipo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group text-right">
                            <div class="col-md-offset-2 col-md-10">
                                <a class="btn btn-primary" href="@Url.Action("Index", "SolicitudProveedores")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                                |
                                <button type="submit" class="btn btn-default"><i class="fas fa-magic ml-1"></i> Crear </button>
                            </div>
                        </div>
                    </div>
                }
                
                @Scripts.Render("~/bundles/jquery")
                @Scripts.Render("~/bundles/bootstrap")
                @Scripts.Render("~/bundles/jsmaterial")

                <script type="text/javascript">
                    $('#Fecha_Ingreso').pickadate({

                        // Strings and translations
                        monthsFull: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre',
                            'Noviembre', 'Diciembre'],
                        monthsShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
                        weekdaysFull: ['Domingo', 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado'],
                        weekdaysShort: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'],

                        autoclose: true,
                        default: 'now',
                        donetext: 'Hecho',

                        // Botones
                        today: 'Hoy',
                        clear: 'Limpiar',
                        close: 'Cerrar',

                        // Formato
                        format: 'yyyy/mm/dd'

                    });
                    $('#Fecha_Creacion').pickadate({

                        // Strings and translations
                        monthsFull: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre',
                            'Noviembre', 'Diciembre'],
                        monthsShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
                        weekdaysFull: ['Domingo', 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado'],
                        weekdaysShort: ['Dom', 'Lun', 'Mar', 'Mie', 'Jue', 'Vie', 'Sab'],

                        autoclose: true,
                        'default': 'now',
                        donetext: 'Hecho',

                        // Botones
                        today: 'Hoy',
                        clear: 'Limpiar',
                        close: 'Cerrar',

                        // Formato
                        format: 'yyyy/mm/dd'

                    }); 
                    $('#Hora_Ingreso').pickatime({
                        autoclose: true,
                        'default': 'now',
                        donetext: 'Hecho',
                        twelvehour: false
                    }); 
                </script>
            </div>
        </div>
    </div>
}

ERP_Mensajeria/Views/SolicitudProveedores/Delete.cshtml
@model ERP_Mensajeria.Models.SolicitudProveedor

@{
    ViewBag.Title = "Eliminar solicitud de proveedor";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span><a href="@Url.Action("Index", "SolicitudProveedores")">Solicitudes de proveedor</a></span>
                    <span>/</span>
                    <span>Eliminar solicitud de proveedor</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                <div>
                    <h4>Solicitud de proveedor existente</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Fecha_Ingreso)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Fecha_Ingreso)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Hora_Ingreso)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Hora_Ingreso)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Fecha_Creacion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Fecha_Creacion)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Descripcion_Corta)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Descripcion_Corta)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Elevador)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Elevador)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Estado_Entrega)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Estado_Entrega)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Entregado)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Entregado)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Aprobado)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Aprobado)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Tipo)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Tipo)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Proveedor.Nombre)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Proveedor.Nombre)
                        </dd>

                    </dl>

                    <hr />
                    <div class="text-center">
                        <h3>¿Desea eliminar ésta solicitud de proveedor?</h3>
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <a class="btn btn-primary" href="@Url.Action("Index", "SolicitudProveedores")">
                                    <i class="fa fa-arrow-left mr-1"></i> Regresar
                                </a>
                                |
                                <button type="submit" class="btn btn-danger">
                                    <i class="fa fa-times mr-1"></i>
                                    Eliminar
                                </button>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}

ERP_Mensajeria/Views/SolicitudProveedores/Details.cshtml
@model ERP_Mensajeria.Models.SolicitudProveedor

@{
    ViewBag.Title = "Detalle de la solicitud del proveedor";
}
@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span><a href="@Url.Action("Index", "SolicitudProveedores")">Solicitudes de proveedor</a></span>
                    <span>/</span>
                    <span>Detalles de la solicitud del proveedor</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">

                <div>
                    <h4>Solicitud de proveedor existente</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Fecha_Ingreso)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Fecha_Ingreso)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Hora_Ingreso)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Hora_Ingreso)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Fecha_Creacion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Fecha_Creacion)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Descripcion_Corta)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Descripcion_Corta)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Elevador)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Elevador)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Estado_Entrega)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Estado_Entrega)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Entregado)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Entregado)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Aprobado)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Aprobado)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Tipo)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Tipo)
                        </dd>

                        <dt>
                            Proveedor
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Proveedor.Nombre)
                        </dd>

                    </dl>
                </div>
                <br />
                <div class="form-group text-right">
                    <div class="col-md-offset-2 col-md-10">
                        <a class="btn btn-primary" href="@Url.Action("Index", "SolicitudProveedores")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                        |
                        <a href="@Url.Action("Edit", "SolicitudProveedores", new { id = Model.ID_SolicitudProveedor})" class="btn btn-default"><i class="fa fa-edit ml-1"></i> Editar </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

ERP_Mensajeria/Views/SolicitudProveedores/Index.cshtml
@model IEnumerable<ERP_Mensajeria.Models.SolicitudProveedor>

@{
    ViewBag.Title = "Inicio";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span>Solicitudes de proveedor</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">

                <div class="row">
                    <div class="col-md-10">
                        <h2>Listado de solicitudes de proveedor</h2>
                    </div>
                    <div class="col-md-2">
                        <a class="btn btn-default btn-rounded" href="@Url.Action("Create", "SolicitudProveedores")">
                            <i class="fa fa-plus"></i> Crear
                        </a>
                    </div>
                </div>
                <br />
                <div class="table-responsive ">
                    <table class="table table-hover ">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Fecha_Ingreso)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Hora_Ingreso)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Fecha_Creacion)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Descripcion_Corta)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Elevador)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Estado_Entrega)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Entregado)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Aprobado)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Tipo)
                            </th>
                            <th>
                                Proveedor
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Fecha_Ingreso)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Hora_Ingreso)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Fecha_Creacion)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Descripcion_Corta)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Elevador)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Estado_Entrega)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Entregado)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Aprobado)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Tipo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Proveedor.Nombre)
                                </td>
                                <td>
                                    <a class="btn btn-sm green" href="@Url.Action("Edit", "SolicitudProveedores", new { id = item.ID_SolicitudProveedor })">
                                        <i class="fa fa-edit"></i> Editar
                                    </a>
                                    <a class="btn btn-sm blue" href="@Url.Action("Details", "SolicitudProveedores", new { id = item.ID_SolicitudProveedor })">
                                        <i class="fa fa-eye"></i> Detalle
                                    </a>
                                    <a class="btn btn-sm red" href="@Url.Action("Delete", "SolicitudProveedores", new { id = item.ID_SolicitudProveedor })">
                                        <i class="fa fa-trash"></i> Eliminar
                                    </a>
                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
}