ERP_Mensajeria/Models/Paquete.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Mensajeria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Paquete
    {
        public int ID_Paquete { get; set; }

        [Display(Name = "Solicitud de proveedor")]
        [DisplayName("Solicitud de proveedor")]
        [Required(ErrorMessage = "Debe seleccionar la solicitud del proveedor")]
        public int ID_SolicitudProveedor { get; set; }

        [DisplayName("Descripción corta")]
        [DataType(DataType.MultilineText)]
        public string Descripcion { get; set; }

        [DisplayName("Detalle del paquete")]
        [DataType(DataType.MultilineText)]
        public string Detalle { get; set; }

        [DefaultValue("Activo")]
        [StringLength(8, MinimumLength = 6)]
        [DisplayName("Estado")]
        [Required(ErrorMessage = "Debe seleccionar el estado del paquete")]
        public string Estado { get; set; }

        [DisplayName("Descripción extra")]
        [DataType(DataType.MultilineText)]
        public string Extra { get; set; }
    
        public virtual SolicitudProveedor SolicitudProveedor { get; set; }
    }
}

ERP_Mensajeria/Controllers/PaquetesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ERP_Mensajeria.Models;

namespace ERP_Mensajeria.Controllers
{
    public class PaquetesController : Controller
    {
        private ERPMensajeriaEntities db = new ERPMensajeriaEntities();

        // GET: Paquetes
        public ActionResult Index()
        {
            var paquete = db.Paquete.Include(p => p.SolicitudProveedor);
            return View(paquete.ToList());
        }

        // GET: Paquetes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paquete paquete = db.Paquete.Find(id);
            if (paquete == null)
            {
                return HttpNotFound();
            }
            return View(paquete);
        }

        // GET: Paquetes/Create
        public ActionResult Create()
        {
            ViewBag.ID_SolicitudProveedor = new SelectList(db.SolicitudProveedor, "ID_SolicitudProveedor", "Descripcion_Corta");
            return View();
        }

        // POST: Paquetes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Paquete,ID_SolicitudProveedor,Descripcion,Detalle,Estado,Extra")] Paquete paquete)
        {
            if (ModelState.IsValid)
            {
                db.Paquete.Add(paquete);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_SolicitudProveedor = new SelectList(db.SolicitudProveedor, "ID_SolicitudProveedor", "Descripcion_Corta", paquete.ID_SolicitudProveedor);
            return View(paquete);
        }

        // GET: Paquetes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paquete paquete = db.Paquete.Find(id);
            if (paquete == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_SolicitudProveedor = new SelectList(db.SolicitudProveedor, "ID_SolicitudProveedor", "Descripcion_Corta", paquete.ID_SolicitudProveedor);
            return View(paquete);
        }

        // POST: Paquetes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Paquete,ID_SolicitudProveedor,Descripcion,Detalle,Estado,Extra")] Paquete paquete)
        {
            if (ModelState.IsValid)
            {
                db.Entry(paquete).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_SolicitudProveedor = new SelectList(db.SolicitudProveedor, "ID_SolicitudProveedor", "Descripcion_Corta", paquete.ID_SolicitudProveedor);
            return View(paquete);
        }

        // GET: Paquetes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paquete paquete = db.Paquete.Find(id);
            if (paquete == null)
            {
                return HttpNotFound();
            }
            return View(paquete);
        }

        // POST: Paquetes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Paquete paquete = db.Paquete.Find(id);
            db.Paquete.Remove(paquete);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ERP_Mensajeria/Views/Paquetes/Create.cshtml
@model ERP_Mensajeria.Models.Paquete
@{
    ViewBag.Title = "Crear paquete";
}
@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span><a href="@Url.Action("Index", "Paquetes")">Paquetes</a></span>
                    <span>/</span>
                    <span>Agregar paquete</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Paquete nuevo</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.ID_SolicitudProveedor, "Solicitud de proveedor", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.DropDownList("ID_SolicitudProveedor", null, htmlAttributes: new { @class = "md-form mdb-select" })
                                @Html.ValidationMessageFor(model => model.ID_SolicitudProveedor, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control md-textarea" } })
                                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Detalle, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Detalle, new { htmlAttributes = new { @class = "form-control md-textarea" } })
                                @Html.ValidationMessageFor(model => model.Detalle, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Estado, new SelectList(new List<Object>{
                                    new { value = "Activo" , text = "Activo"  },
                                    new { value = "Inactivo" , text = "Inactivo" }},
                                    "value", "text", 2), new { @class = "mdb-select md-form" })
                                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Extra, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Extra, new { htmlAttributes = new { @class = "form-control md-textarea" } })
                                @Html.ValidationMessageFor(model => model.Extra, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group text-right">
                            <div class="col-md-offset-2 col-md-10">
                                <a class="btn btn-primary" href="@Url.Action("Index", "Empresas")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                                |
                                <button type="submit" class="btn btn-default"><i class="fas fa-magic ml-1"></i> Crear </button>
                            </div>
                        </div>
                    </div>
                }

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }
            </div>
        </div>
    </div>
}

ERP_Mensajeria/Views/Paquetes/Delete.cshtml
@model ERP_Mensajeria.Models.Paquete

@{
    ViewBag.Title = "Eliminar paquete";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span><a href="@Url.Action("Index", "Paquetes")">Paquetes</a></span>
                    <span>/</span>
                    <span>Eliminar paquete</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                <div>
                    <h4>Paquete existente</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Descripcion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Descripcion)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Detalle)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Detalle)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Estado)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Estado)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Extra)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Extra)
                        </dd>

                        <dt>
                            Solicitud de Proveedor
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.SolicitudProveedor.Descripcion_Corta)
                        </dd>

                    </dl>

                    <hr />
                    <div class="text-center">
                        <h3>¿Desea eliminar éste paquete?</h3>
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <a class="btn btn-primary" href="@Url.Action("Index", "Paquetes")">
                                    <i class="fa fa-arrow-left mr-1"></i> Regresar
                                </a>
                                |
                                <button type="submit" class="btn btn-danger">
                                    <i class="fa fa-times mr-1"></i>
                                    Eliminar
                                </button>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}

ERP_Mensajeria/Views/Paquetes/Details.cshtml
@model ERP_Mensajeria.Models.Paquete

@{
    ViewBag.Title = "Detalles del paquete";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span><a href="@Url.Action("Index", "Paquetes")">Paquetes</a></span>
                    <span>/</span>
                    <span>Detalles del paquete</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                <div>
                    <h4>Paquete existente</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Descripcion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Descripcion)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Detalle)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Detalle)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Estado)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Estado)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Extra)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Extra)
                        </dd>

                        <dt>
                            Solicitud de proveedor
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.SolicitudProveedor.Descripcion_Corta)
                        </dd>

                    </dl>
                </div>
                <br />
                <div class="form-group text-right">
                    <div class="col-md-offset-2 col-md-10">
                        <a class="btn btn-primary" href="@Url.Action("Index", "Paquetes")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                        |
                        <a href="@Url.Action("Edit", "Paquetes", new { id = Model.ID_Paquete})" class="btn btn-default"><i class="fa fa-edit ml-1"></i> Editar </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

ERP_Mensajeria/Views/Paquetes/Edit.cshtml
@model ERP_Mensajeria.Models.Paquete

@{
    ViewBag.Title = "Editar paquete";
}
@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span><a href="@Url.Action("Index", "Paquetes")">Paquetes</a></span>
                    <span>/</span>
                    <span>Editar paquete</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Paquete existente</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.ID_Paquete)

                        <div class="form-group">
                            @Html.LabelFor(model => model.ID_SolicitudProveedor, "Solicitud de proveedor", htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.DropDownList("ID_SolicitudProveedor", null, htmlAttributes: new { @class = "md-form mdb-select" })
                                @Html.ValidationMessageFor(model => model.ID_SolicitudProveedor, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control md-textarea" } })
                                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Detalle, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Detalle, new { htmlAttributes = new { @class = "form-control md-textarea" } })
                                @Html.ValidationMessageFor(model => model.Detalle, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Estado, new SelectList(new List<Object>{
                                    new { value = "Activo" , text = "Activo"  },
                                    new { value = "Inactivo" , text = "Inactivo" }},
                                    "value", "text", 2), new { @class = "mdb-select md-form" })
                                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Extra, htmlAttributes: new { @class = "control-label col-md-4" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Extra, new { htmlAttributes = new { @class = "form-control md-textarea" } })
                                @Html.ValidationMessageFor(model => model.Extra, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group text-right">
                            <div class="col-md-offset-2 col-md-10">
                                <a class="btn btn-primary" href="@Url.Action("Index", "Paquetes")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                                |
                                <button type="submit" class="btn btn-default"><i class="fa fa-save ml-1"></i> Guardar </button>
                            </div>
                        </div>
                    </div>
                }

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }
            </div>
        </div>
    </div>
}

ERP_Mensajeria/Views/Paquetes/Index.cshtml
@model IEnumerable<ERP_Mensajeria.Models.Paquete>
@{
    ViewBag.Title = "Inicio";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span>Paquetes</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">

                <div class="row">
                    <div class="col-md-10">
                        <h2>Listado de paquetes</h2>
                    </div>
                    <div class="col-md-2">
                        <a class="btn btn-default btn-rounded" href="@Url.Action("Create", "Paquetes")">
                            <i class="fa fa-plus"></i> Crear
                        </a>
                    </div>
                </div>
                <br />
                <div class="table-responsive ">
                    <table class="table table-hover ">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Descripcion)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Detalle)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Estado)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Extra)
                            </th>
                            <th>
                                Solicitud de proveedor
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Descripcion)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Detalle)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Estado)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Extra)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SolicitudProveedor.Descripcion_Corta)
                                </td>
                                <td>
                                    <a class="btn btn-sm green" href="@Url.Action("Edit", "Paquetes", new { id = item.ID_Paquete })">
                                        <i class="fa fa-edit"></i> Editar
                                    </a>
                                    <a class="btn btn-sm blue" href="@Url.Action("Details", "Paquetes", new { id = item.ID_Paquete })">
                                        <i class="fa fa-eye"></i> Detalle
                                    </a>
                                    <a class="btn btn-sm red" href="@Url.Action("Delete", "Paquetes", new { id = item.ID_Paquete })">
                                        <i class="fa fa-trash"></i> Eliminar
                                    </a>
                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
}