ERP_Mensajeria/Models/RutaEntrega.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Mensajeria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RutaEntrega
    {
        public int ID_RutaEntrega { get; set; }

        [Display(Name = "Empresa")]
        [Required(ErrorMessage = "Debe seleccionar la empresa")]
        public int ID_Empresa { get; set; }

        [Display(Name ="Proveedor")]
        [Required(ErrorMessage = "Debe seleccionar el proveedor")]
        public int ID_Proveedor { get; set; }

        [StringLength(11, MinimumLength = 10)]
        [Display(Name = "Orden")]
        [Required(ErrorMessage = "Debe seleccionar el orden")]
        public string ORDEN { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}

ERP_Mensajeria/Controllers/RutaEntregasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ERP_Mensajeria.Models;

namespace ERP_Mensajeria.Controllers
{
    public class RutaEntregasController : Controller
    {
        private ERPMensajeriaEntities db = new ERPMensajeriaEntities();

        // GET: RutaEntregas
        public ActionResult Index()
        {
            var rutaEntrega = db.RutaEntrega.Include(r => r.Empresa).Include(r => r.Proveedor);
            return View(rutaEntrega.ToList());
        }

        // GET: RutaEntregas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RutaEntrega rutaEntrega = db.RutaEntrega.Find(id);
            if (rutaEntrega == null)
            {
                return HttpNotFound();
            }
            return View(rutaEntrega);
        }

        // GET: RutaEntregas/Create
        public ActionResult Create()
        {
            ViewBag.ID_Empresa = new SelectList(db.Empresa, "ID_Empresa", "Nombre");
            ViewBag.ID_Proveedor = new SelectList(db.Proveedor, "ID_Proveedor", "Nombre");
            return View();
        }

        // POST: RutaEntregas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_RutaEntrega,ID_Empresa,ID_Proveedor,ORDEN")] RutaEntrega rutaEntrega)
        {
            if (ModelState.IsValid)
            {
                db.RutaEntrega.Add(rutaEntrega);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_Empresa = new SelectList(db.Empresa, "ID_Empresa", "Nombre", rutaEntrega.ID_Empresa);
            ViewBag.ID_Proveedor = new SelectList(db.Proveedor, "ID_Proveedor", "Nombre", rutaEntrega.ID_Proveedor);
            return View(rutaEntrega);
        }

        // GET: RutaEntregas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RutaEntrega rutaEntrega = db.RutaEntrega.Find(id);
            if (rutaEntrega == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Empresa = new SelectList(db.Empresa, "ID_Empresa", "Nombre", rutaEntrega.ID_Empresa);
            ViewBag.ID_Proveedor = new SelectList(db.Proveedor, "ID_Proveedor", "Nombre", rutaEntrega.ID_Proveedor);
            return View(rutaEntrega);
        }

        // POST: RutaEntregas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_RutaEntrega,ID_Empresa,ID_Proveedor,ORDEN")] RutaEntrega rutaEntrega)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rutaEntrega).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Empresa = new SelectList(db.Empresa, "ID_Empresa", "Nombre", rutaEntrega.ID_Empresa);
            ViewBag.ID_Proveedor = new SelectList(db.Proveedor, "ID_Proveedor", "Nombre", rutaEntrega.ID_Proveedor);
            return View(rutaEntrega);
        }

        // GET: RutaEntregas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RutaEntrega rutaEntrega = db.RutaEntrega.Find(id);
            if (rutaEntrega == null)
            {
                return HttpNotFound();
            }
            return View(rutaEntrega);
        }

        // POST: RutaEntregas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RutaEntrega rutaEntrega = db.RutaEntrega.Find(id);
            db.RutaEntrega.Remove(rutaEntrega);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ERP_Mensajeria/Views/RutaEntregas/Create.cshtml
@model ERP_Mensajeria.Models.RutaEntrega

@{
    ViewBag.Title = "Crear ruta de entrega";
}
@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span><a href="@Url.Action("Index", "RutaEntregas")">Rutas de entrega</a></span>
                    <span>/</span>
                    <span>Agregar ruta de entrega</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Ruta de entrega nueva</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.ID_Empresa, "Empresa", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("ID_Empresa", null, htmlAttributes: new { @class = "md-form mdb-select" })
                                @Html.ValidationMessageFor(model => model.ID_Empresa, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ID_Proveedor, "Proveedor", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("ID_Proveedor", null, htmlAttributes: new { @class = "md-form mdb-select" })
                                @Html.ValidationMessageFor(model => model.ID_Proveedor, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ORDEN, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.ORDEN, new SelectList(new List<Object>{
                                    new { value = "Ascendente" , text = "Ascendente"  },
                                    new { value = "Descendente" , text = "Descendente" }},
                                    "value", "text", 2), new { @class = "mdb-select md-form" })
                                @Html.ValidationMessageFor(model => model.ORDEN, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group text-right">
                            <div class="col-md-offset-2 col-md-10">
                                <a class="btn btn-primary" href="@Url.Action("Index", "RutaEntregas")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                                |
                                <button type="submit" class="btn btn-default"><i class="fas fa-magic ml-1"></i> Crear </button>
                            </div>
                        </div>
                    </div>
                }

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }
            </div>
        </div>
    </div>
}

ERP_Mensajeria/Views/RutaEntregas/Delete.cshtml
@model ERP_Mensajeria.Models.RutaEntrega

@{
    ViewBag.Title = "Eliminar ruta de entrega";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span><a href="@Url.Action("Index", "RutaEntregas")">Rutas de entrega</a></span>
                    <span>/</span>
                    <span>Eliminar ruta de entrega</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                <div>
                    <h4>Ruta de entrega existente</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.ORDEN)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.ORDEN)
                        </dd>

                        <dt>
                            Empresa
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Empresa.Nombre)
                        </dd>

                        <dt>
                            Proveedor
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Proveedor.Nombre)
                        </dd>

                    </dl>

                    <hr />
                    <div class="text-center">
                        <h3>¿Desea eliminar ésta ruta de entrega?</h3>
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <a class="btn btn-primary" href="@Url.Action("Index", "RutaEntregas")">
                                    <i class="fa fa-arrow-left mr-1"></i> Regresar
                                </a>
                                |
                                <button type="submit" class="btn btn-danger">
                                    <i class="fa fa-times mr-1"></i>
                                    Eliminar
                                </button>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}

ERP_Mensajeria/Views/RutaEntregas/Details.cshtml
@model ERP_Mensajeria.Models.RutaEntrega

@{
    ViewBag.Title = "Detalles de la ruta de entrega";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span><a href="@Url.Action("Index", "RutaEntregas")">Rutas de entrega</a></span>
                    <span>/</span>
                    <span>Detalles de la ruta de entrega</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                <div>
                    <h4>Ruta de entrega</h4>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.ORDEN)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.ORDEN)
                        </dd>

                        <dt>
                            Empresa
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Empresa.Nombre)
                        </dd>

                        <dt>
                            Proveedor
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Proveedor.Nombre)
                        </dd>

                    </dl>
                </div>
                <br />
                <div class="form-group text-right">
                    <div class="col-md-offset-2 col-md-10">
                        <a class="btn btn-primary" href="@Url.Action("Index", "RutaEntregas")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                        |
                        <a href="@Url.Action("Edit", "RutaEntregas", new { id = Model.ID_RutaEntrega})" class="btn btn-default"><i class="fa fa-edit ml-1"></i> Editar </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

ERP_Mensajeria/Views/RutaEntregas/Edit.cshtml
@model ERP_Mensajeria.Models.RutaEntrega

@{
    ViewBag.Title = "Editar ruta de entrega";
}
@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span><a href="@Url.Action("Index", "RutaEntregas")">Rutas de entrega</a></span>
                    <span>/</span>
                    <span>Editar ruta de entrega</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>Ruta de netrega existente</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.ID_RutaEntrega)

                        <div class="form-group">
                            @Html.LabelFor(model => model.ID_Empresa, "Empresa", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("ID_Empresa", null, htmlAttributes: new { @class = "md-form mdb-select" })
                                @Html.ValidationMessageFor(model => model.ID_Empresa, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ID_Proveedor, "Proveedor", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("ID_Proveedor", null, htmlAttributes: new { @class = "mdb-select md-form" })
                                @Html.ValidationMessageFor(model => model.ID_Proveedor, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.ORDEN, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.ORDEN, new SelectList(new List<Object>{
                                    new { value = "Ascendente" , text = "Ascendente"  },
                                    new { value = "Descendente" , text = "Descendente" }},
                                    "value", "text", 2), new { @class = "mdb-select md-form" })
                                @Html.ValidationMessageFor(model => model.ORDEN, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group text-right">
                            <div class="col-md-offset-2 col-md-10">
                                <a class="btn btn-primary" href="@Url.Action("Index", "RutaEntregas")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                                |
                                <button type="submit" class="btn btn-default"><i class="fa fa-save ml-1"></i> Guardar </button>
                            </div>
                        </div>
                    </div>
                }

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }
            </div>
        </div>
    </div>
}

ERP_Mensajeria/Views/RutaEntregas/Index.cshtml
@model IEnumerable<ERP_Mensajeria.Models.RutaEntrega>

@{
    ViewBag.Title = "Inicio";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="container-fluid mt-5">
        <div class="card mb-4 wow fadeIn">
            <div class="card-body d-sm-flex justify-content-between">
                <h4 class="mb-2 mb-sm-0 pt-1">
                    <span><a href="@Url.Action("Index", "Home")">Inicio</a></span>
                    <span>/</span>
                    <span>Rutas de entrega</span>
                </h4>
            </div>
        </div>

        <div class="card mb-4 wow fadeIn">
            <div class="card-body">

                <div class="row">
                    <div class="col-md-10">
                        <h2>Listado de rutas de entrega</h2>
                    </div>
                    <div class="col-md-2">
                        <a class="btn btn-default btn-rounded" href="@Url.Action("Create", "RutaEntregas")">
                            <i class="fa fa-plus"></i> Crear
                        </a>
                    </div>
                </div>
                <br />
                <div class="table-responsive ">
                    <table class="table table-hover ">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.ORDEN)
                            </th>
                            <th>
                                Empresa
                            </th>
                            <th>
                                Proveedor
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ORDEN)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Empresa.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Proveedor.Nombre)
                                </td>
                                <td>
                                    <a class="btn btn-sm green" href="@Url.Action("Edit", "RutaEntregas", new { id = item.ID_RutaEntrega })">
                                        <i class="fa fa-edit"></i> Editar
                                    </a>
                                    <a class="btn btn-sm blue" href="@Url.Action("Details", "RutaEntregas", new { id = item.ID_RutaEntrega })">
                                        <i class="fa fa-eye"></i> Detalle
                                    </a>
                                    <a class="btn btn-sm red" href="@Url.Action("Delete", "RutaEntregas", new { id = item.ID_RutaEntrega })">
                                        <i class="fa fa-trash"></i> Eliminar
                                    </a>
                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
}